### ISSUE TITLE
TS file '.' adds the first item.

### ISSUE THREAD

**Issue by TheColorRed** [Jerry-Hong/vscode-autofilename#1]
When I use this plugin, and I need to go up a folder, or stay in the current folder, and I press <kbd>.</kbd> in a `.ts` file it automatically adds the first item if the quote isn't closed.

``` ts
import { MyClass } from ';
```

**Comment by Jerry-Hong** [comment]
OK! I will fix it

**Comment by Jerry-Hong** [comment]
@TheColorRed Thanks you feedback this issue!
It is fix on 0.1.0 version. you can update it now
