### ISSUE TITLE
When auto filename is installed, quick suggestions won't work anymore.

### ISSUE THREAD

**Issue by JonathanStoye** [Jerry-Hong/vscode-autofilename#10]
Maybe I am missing something here, but it seems, that autoFileName is preventing quicksuggestions from working.

Good:
![1d4cd1](https://cloud.githubusercontent.com/assets/21689428/19799749/921217e4-9cf8-11e6-9716-1d1d789a41d2.gif)

Bad:
![1d4cee](https://cloud.githubusercontent.com/assets/21689428/19799755/98e8632a-9cf8-11e6-972e-18e0f313b46f.gif)

**Comment by Jerry-Hong** [comment]
I can not trig this error.
Could you provide more detail?

**Comment by JonathanStoye** [comment]
I have a clean VS Code Installation on OS X and the moment I install auto filename there are no suggestions anymore from inside the file as VS Code is doing it normally.

**Comment by atombender** [comment]
I can confirm that this extension breaks things. See [this VSCode issue](https://github.com/Microsoft/vscode/issues/15411#issuecomment-260397549) for a more in-depth explanation. I disabled all extensions except this one to pinpoint the cause.

**Comment by jrieken** [comment]
Fyi - this is VS Code issue and fixed on master.

**Comment by jrieken** [comment]
@JonathanStoye  Tho one thing I have noticed using the extension is that it adds completion items without labels. They then show as `<missing label>` in the UI

**Comment by Jerry-Hong** [comment]
@jrieken Yes, it is just a hack skill for .ts file.
