### ISSUE TITLE
Remove file extension it TS files

### ISSUE THREAD

**Issue by TheColorRed** [Jerry-Hong/vscode-autofilename#3]
In TypeScript, when importing files using the import call, it is invalid for files to have the file extension in `es6+`.

``` ts
// Invalid (es6+):
import { MyClass } from '../my/file.ts';

// Valid:
import { MyClass } from '../my/file';
```

**Comment by Jerry-Hong** [comment]
@TheColorRed  look like not this extension cause ?

**Comment by Jerry-Hong** [comment]
@TheColorRed Is there an error message?

**Comment by TheColorRed** [comment]
vscode says:

> Cannot find module '../core/Blueberry.ts'

If I remove the `.ts` it can find the module.

**Comment by Jerry-Hong** [comment]
@TheColorRed I can not trigger this error. 
Thank you feedback this issue, but I don't think AutoFileName cause the error.
Maybe you can try update your typescript or vscode

**Comment by TheColorRed** [comment]
This is not an extension issue, it is a syntax error in `ts` files. So this is a feature request to remove the file extension in `ts` files.
